# Generated by Django 3.1.7 on 2021-02-25 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='customer_user', serialize=False, to='main.user')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_no', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'customer_users',
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division_name', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'db_table': 'division',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(blank=True, max_length=120, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'place',
            },
        ),
        migrations.CreateModel(
            name='ResturantUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='resturant_user', serialize=False, to='main.user')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=120, null=True)),
                ('phone_no', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'resturant_user',
            },
        ),
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='rider_user', serialize=False, to='main.user')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=120, null=True)),
                ('phone_no', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'rider_profile',
            },
        ),
        migrations.CreateModel(
            name='ResturrantPosition',
            fields=[
                ('rest_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='resturant_pos', serialize=False, to='main.resturantuser')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rest_place', to='main.place')),
            ],
            options={
                'db_table': 'resturant_place',
            },
        ),
    ]
