# Generated by Django 3.1.7 on 2021-02-25 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_customer_division_place_resturantuser_resturrantposition_rider'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ResturrantPosition',
            new_name='ResturantPosition',
        ),
    ]
