# Generated by Django 3.1.7 on 2021-02-26 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_customer_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodname',
            name='food_description',
        ),
        migrations.AddField(
            model_name='place',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.division'),
        ),
    ]
