# Generated by Django 3.1.7 on 2021-02-26 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210226_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='age',
        ),
    ]
