# Generated by Django 3.1.7 on 2021-02-28 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_customer_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodname',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.resturantuser'),
        ),
    ]
