# Generated by Django 3.1.7 on 2021-02-28 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_resturantuser_resturant_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='resturantuser',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='resturantuser',
            name='menu_list',
            field=models.ImageField(null=True, upload_to='food/image/'),
        ),
    ]
