# Generated by Django 3.1.7 on 2021-03-01 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20210228_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='resturantuser',
            name='resturant_front',
            field=models.ImageField(null=True, upload_to='food/resturant/'),
        ),
    ]
