# Generated by Django 3.1.7 on 2021-04-28 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_resturantuser_resturant_front'),
    ]

    operations = [
        migrations.CreateModel(
            name='allowResturant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(blank=True, max_length=120, null=True)),
                ('first_name', models.CharField(blank=True, max_length=120, null=True)),
                ('last_name', models.CharField(blank=True, max_length=120, null=True)),
                ('resturant_name', models.CharField(blank=True, max_length=120, null=True)),
                ('resturant_front', models.ImageField(null=True, upload_to='food/resturant/')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_no', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('menu_list', models.ImageField(null=True, upload_to='food/add/')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.place')),
            ],
            options={
                'db_table': 'allow_user',
            },
        ),
    ]
