# Generated by Django 3.1.7 on 2021-05-10 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20210509_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='process',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='to_rider',
            field=models.BooleanField(default=False),
        ),
    ]
