# Generated by Django 3.1.7 on 2021-05-10 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_order_delivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
